
version: 2

models:
  - name: films
    description: "This table contain about films"
    columns:
      - name: film_id
        description: "Unique identifier for the films"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Date the film was realse"
        tests:
          - not_null
      - name: price
        description: "Price to buy a ticket of the film"
        tests:
          - not_null
      - name: rating
        description: "The MMPA rating of the film"
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film"
        tests:
          - not_null

  - name: actors
    description: "This table contain detail about actors"
    columns:
      - name: actor_id
        description: "Unique identifier for the actors"
        tests:
          - unique
          - not_null
      - name: name
        description: "First name of the actor"
        tests:

  - name: film_actors
    description: "The table maps films to the actor that starred in them"
    columns:
      - name: film_id
        description: "Identifier for the films"
        tests:
          - unique
          - not_null
      - name: actor_id
        description: "Identifier for the actor"
        tests:
          - not_null

  - name: film_ratings
    description: "This model aggregayes film data and calculates the average rating for each film"
    columns:
      - name: film_id
        description: "Unique identifier for the films"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Date the film was realse"
        tests:
          - not_null
      - name: price
        description: "Price to buy a ticket of the film"
        tests:
          - not_null
      - name: rating
        description: "The MMPA rating of the film"
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film"
        tests:
          - not_null
      - name: actor_count
        description: "The number of the actors in the film"
        tests:
          - not_null
      - name: avg_actor_rating
        description: "The average rating of the film that the actors of this film have acted in"
        tests:
          - not_null